version: '2'
services:

  flask-example:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/flask-example
    user: root
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development

