version: '2'
services:

  videofaces-frontend:
    image: peterg11/ssdd:frontend
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
      - BACKEND_REST=backend-rest
      - SQL_SERVER=videofaces-mysql
      - GRPC_SERVER=videofaces-grpc
      - GRPC_SERVER_PORT=50051

  videofaces-mysql:
    image: peterg11/ssdd:videofaces
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=videofaces

  backend-rest:
    image: peterg11/ssdd:backend-rest
    ports:
      - 8080:8080
    environment:
      - SQL_SERVER=videofaces-mysql
      - GRPC_SERVER=videofaces-grpc
      - GRPC_SERVER_PORT=50051

  videofaces-grpc:
    image: peterg11/ssdd:backend-grpc
    ports:
      - 50051
    environment:
      - SQL_SERVER=videofaces-mysql
      - GRPC_SERVER=videofaces-grpc
      - GRPC_SERVER_PORT=50051


